# Generated by Django 5.2.3 on 2025-06-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='evaluador',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha_evaluacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='proyecto',
        ),
    ]
